### ISSUE TITLE
Hi,body, How can I modify the includedir?

### ISSUE THREAD

**Issue by Shaco-Ma** [ASPLes/nopoll#13]
Hi , man:
     I use the nopoll package in ubuntu,and autogen.sh ,make, sudo make install, but it will creat a dir who name is nopoll in /usr/include, so when I use it ,I #include<nopoll.h> ,it can't complie ok,
     so, can you tell how to do I can change the '.h' files dir?like this /usr/include/nopoll.h and so on, not to creat dir in /usr/include.

**Comment by Shaco-Ma** [comment]
I do like this --includedir=/usr/include,but it will make dir in /usr/include......

**Comment by francisbrosnan** [comment]
See the following link for more information (how to get compilation flags):
http://www.aspl.es/nopoll/html/nopoll_core_library_manual.html#using_nopoll

**Comment by francisbrosnan** [comment]
noPoll compilation files are not prepared to drop all files directly into /usr/include  (it is not recommended). Even though it is not supported by us, try to modify configure.ac and all Makefile.am to make it so...but, as I say, we really not recommend it (bit is best to stick to this scheme),
Best Regards,

**Comment by Shaco-Ma** [comment]
Hello:
        I am so sorry so late to back this email.
        Now I had modify some files in nopoll, and now I can use it in openwrt, and very thanks U give me some idea.






在 2016-12-19 22:34:25，"Francis Brosnan Blázquez" <notifications@github.com> 写道：


noPoll compilation files are not prepared to drop all files directly into /usr/include (it is not recommended). Even though it is not supported by us, try to modify configure.ac and all Makefile.am to make it so...but, as I say, we really not recommend it (bit is best to stick to this scheme),
Best Regards,
