### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by schmidtw** [ASPLes/nopoll#18]
A while back we proposed an IPv6 patch that wasn't accepted.  @francisbrosnan mentioned that they had a mechanism in the works that would match up better.  Can you share (so we can help with this effort) or similar?

Presently we're using an older fork and would like to rebase to use the latest, but we must support IPv6.

Glad to help & thanks!
Wes

**Comment by francisbrosnan** [comment]
Hi Wes,

Ok, noPoll already supports IPv6 through API prefixed with "6". Some of them are:

- nopoll_conn_new6
- nopoll_conn_tls_new6

...and for listeners you have:

   - nopoll_listener_new6
   - nopoll_listener_new_opts6
   - nopoll_listener_tls_new6
   - nopoll_listener_tls_new_opts6

This was included in the last stable release:
http://lists.aspl.es/pipermail/nopoll/2016-December/000159.html

Best Regards

**Comment by schmidtw** [comment]
Fantastic - not sure how I missed this!

**Comment by francisbrosnan** [comment]
Hi Wes,
Hehe, no problem :-) 
Best Regards,
