### ISSUE TITLE
noPollCtx will not be freeed when winsock initialization failed

### ISSUE THREAD

**Issue by jackyzy823** [ASPLes/nopoll#29]
https://github.com/ASPLes/nopoll/blob/84185610cce6b0aec52e0c7e490eb066735a66bd/src/nopoll_ctx.c#L75
```c
#if defined(NOPOLL_OS_WIN32)
	if (! nopoll_win32_init (result))
		return NULL;
#endif
```
it just return `NULL` without free `noPollCtx`  when  winsock initialization failed

**Comment by francisbrosnan** [comment]
Thanks for taking your time and reporting!
