### ISSUE TITLE
Typo in nopoll_conn_opts.c

### ISSUE THREAD

**Issue by HRogge** [ASPLes/nopoll#34]
in line 68 the (not existing) constant NOPOLL_METHOD_TLSV2 is used...

this should be (most likely) NOPOLL_METHOD_TLSV1_2

**Comment by francisbrosnan** [comment]
Hello Henning.
Thanks for reporting. Certain, this was fixed at current latest:
https://github.com/ASPLes/nopoll/blob/master/src/nopoll_conn_opts.c#L68

We should release noPoll 0.4.5 this week (including this fix).
Best Regards.
