### ISSUE TITLE
Wnerror "unitialised" when building for Windows

### ISSUE THREAD

**Issue by dspname** [ASPLes/nopoll#37]
Hello,

_noPollCtx * result_ in line 69 in _nopoll_ctx.c_ is used unitialised. As _autogen.sh_ uses _-Werror_ on automake, compiling for Win32 will fail because of the use in line 72 _if (! nopoll_win32_init (result)) {_ right after. Therefore, _result_ should be initialised with _noPollCtx* result = NULL_, I'd say.

**Comment by francisbrosnan** [comment]
Thanks @dspname 
I've moved win32 initialization after nopoll_new is created.
Best Regards.
