### ISSUE TITLE
Type of payload in nopoll API should be a `void` not a `char`

### ISSUE THREAD

**Issue by cableramki** [ASPLes/nopoll#48]
https://github.com/ASPLes/nopoll/pull/47 worked around following error on Mac OS:

```
nopoll-regression-client.c:1681:14: error: implicit conversion from 'int' to 'char' changes value from 129 to -127 [-Werror,-Wconstant-conversion]
        buffer[0] = 129;
                  ~ ^~~
nopoll-regression-client.c:1682:14: error: implicit conversion from 'int' to 'char' changes value from 150 to -106 [-Werror,-Wconstant-conversion]
        buffer[1] = 150;
                  ~ ^~~
2 errors generated.
``` 

If the payload type in all applicable [API](https://github.com/ASPLes/nopoll/blob/master/src/nopoll_conn.h) were to be `void`, then any type of data may be used without error.

**Comment by francisbrosnan** [comment]
Hello @cableramki 
This is an historic issue we can't change due to API is already in production.
At the same time, it is an issue that can be easily solved by casting.
I'm closing this issue.
Best Regards.
