### ISSUE TITLE
Memory leak observed in nopoll_conn_send_frame 

### ISSUE THREAD

**Issue by selvamKrish** [ASPLes/nopoll#52]
Memory allocated for send_buffer https://github.com/ASPLes/nopoll/blob/master/src/nopoll_conn.c#L4428 is not getting freed in error case https://github.com/ASPLes/nopoll/blob/master/src/nopoll_conn.c#L4496.

**Comment by francisbrosnan** [comment]
Memory pointed by report is stack allocated (not in the heap). It cannot freed, so nothing has to be done in error case. Best Regards
