### ISSUE TITLE
[nopoll_conn.c:3197]: nopoll_log() format string requires 2 parameters but only 1 is given.

### ISSUE THREAD

**Issue by qianqiangliu** [ASPLes/nopoll#57]
nopoll_log (conn->ctx, NOPOLL_LEVEL_DEBUG, "Reusing mask value = %d from previous frame (%d)", nopoll_get_32bit (msg->mask));
missing number 2 '%d' parameter

**Comment by francisbrosnan** [comment]
Fixed at https://github.com/ASPLes/nopoll/commit/de20fc877109d3a83c3c25bd6ac70d5c5b3103a7
Thanks for reporting. Best Regards
