### ISSUE TITLE
typo  bug in function nopoll_cmp / nopoll.c line 69

### ISSUE THREAD

**Issue by samisallinen** [ASPLes/nopoll#65]
68	iterator = 0;

69	while (string1[iterator] && string1[iterator]) {

70		if (string1[iterator] != string2[iterator])

Line 69 should probably be changed to:
	while (string1[iterator] && string2[iterator]) {

2nd 'string1' should probably be 'string2'

**Comment by francisbrosnan** [comment]
You are right, thanks for reporting @samisallinen
