### ISSUE TITLE
Secure Websocket connection issue with  react-native client

### ISSUE THREAD

**Issue by sandeepReddyG** [ASPLes/nopoll#68]
Hi,
I am trying to establish a secure websocket connection between mobile and PC using the test-certificate.crt and test-private.key provided. But the SSL handshake is getting failed with the
error message "**Hostname 192.168.0.5 not verified**:".  Is it ok to use these certificates for my testing or I need to have my own certificate? The strange thing is , the same is working with C and Java based websocket clients.

**Comment by francisbrosnan** [comment]
Hello @sandeepReddyG 

The key thing is certificate verification which is done at client side (could be at server side too, but that will be called mutual verification). Your C/Java clients are not doing certificiate verification and for that reason, they are accepting to connect. 

However, your webbrowser have certificate verification by default (all do). You will have to disable certificate verification at your browser if you want to work with it or install a signed certificate that is trusted by your browser.

For chrome I use the following to start a session that accept connecting to peers with broken certificates:

google-chrome --ignore-certificate-errors --user-data-dir=$HOME/tmp/new-chrome-&#96;date +%s&#96;

Check your browser's documentation to see how it is done.
