### ISSUE TITLE
Build on Window

### ISSUE THREAD

**Issue by 1565430482** [ASPLes/nopoll#72]
hi！how to build this project on windows

**Comment by francisbrosnan** [comment]
Hello,

See: https://github.com/ASPLes/nopoll/blob/master/Makefile.win

It includes instructions on how to compile nopoll using mingw. Other methods aren't investigested though we are aware of users using VS and others tool chains without issues.

Best Regards

**Comment by 1565430482** [comment]
thanks！Can you tell me which version of OpenSSL Windows depends on？
