### ISSUE TITLE
Debian bookworm support

### ISSUE THREAD

**Issue by whitpa** [ASPLes/nopoll#77]
There is no support for Debian/Ubuntu releases later than Bullseye/Focal.

I managed to hack together a debian-files/bookworm folder that did the job.  Changes include:

- add "-Wno-int-to-pointer-cast" to CFLAGS in "rules"
- change "dh_clean -k to "dh_prep" in "rules"
- change "dh_install --list-missing --sourcedir=debian/tmp" to "dh_install --sourcedir=debian/tmp" in "rules"
- add "dh-missing --list-missing --sourcedir=debian/tmp" to "rules" (after the "dh_install" line) in "rules"
- change libssl1.1 to libssl3 in the Depends section of the "control" file 
- change "debhelper (>= 5)" to "debhelper (>= 10)" in the Build-Depends section of the "control" file
- change the compatibility level from 5 to 10 in the "compat" file

FYI: No, I am not willing to submit a Git pull request.  I am a consumer, not a producer, of this Git repository (i.e. tarballs only), and do not wish to host an Internet-accessible Git repo.

**Comment by umaplehurst** [comment]
The above isn't enough to fix the package so it's also multilib-compliant. This is necessary if you want to have other packages automatically depend on the nopoll package. I did the following to fix this:

a) change `debian/rules` to the following:

```
#!/usr/bin/make -f

%:
        dh $@ --with=autoreconf

override_dh_auto_test:
        true
```

b) change `debian/libnopoll0-dev.install` to:

```
usr/include/*
usr/lib/*/lib*.a
usr/lib/*/lib*.so
usr/lib/*/pkgconfig/*
```

c) change `debian/libnopoll0.install` to: `usr/lib/*/lib*.so.*`
d) add `Multi-Arch: same` to libnopoll0 + libnopoll0-dev in `debian/control`
e) bump `debian/compat`

**Comment by francisbrosnan** [comment]
Latest 0.4.9 adds support for these distributions.
http://lists.aspl.es/pipermail/nopoll/2024-October/000251.html
Thanks for reporting
