### ISSUE TITLE
Failed running configure with error: cannot find input file: `src/Makefile.in' with 0.4.7

### ISSUE THREAD

**Issue by wangtao13** [ASPLes/nopoll#78]
I am trying to cross-compile nopoll-0.4.7 in buildroot (running in WSL2 Ubuntu20.04.6).
I failed when running `configure` as follows,
```
configure: creating ./config.status
Host detected: mipsel-buildroot-linux-gnu
config.status: creating Makefile
config.status: error: cannot find input file: `src/Makefile.in'
```

Then I tried to re-run `configure` in WSL2 directly, it still hit the same error,
```
config.status: creating Makefile
config.status: error: cannot find input file: `src/Makefile.in'
```

I checked the src/, there is NO such `Makefile.in`.

So how can I build nopoll in my system (WSL2 and cross-compiling)?

**Comment by francisbrosnan** [comment]
Hello,

That file (src/Makefile.in) is included in all tarballs:

```
>> wget -q https://www.aspl.es/nopoll/downloads/nopoll-0.4.8.b429.tar.gz
>> tar tvf nopoll-0.4.8.b429.tar.gz | grep src/Makefile.in
-rw-rw-r-- 1000/1000     23457 2022-08-26 13:29 nopoll-0.4.8.b429/src/Makefile.in
```

In seems the following error:

`config.status: error: cannot find input file: `src/Makefile.in'`

...has to do with folder location, environment variables or something that is causing **./configure** script to not being able to find src/Makefile.in. 

See **config.log** to find possible causes. 
Best Regards,

**Comment by francisbrosnan** [comment]
> So can i use the same way to build nopoll-0.4.7.b429? And my system is using libssl.so.3, how can I make nopoll to work with it?

Yes, it should be possible without any difference. Best Regards
