### ISSUE TITLE
on autogen.sh

### ISSUE THREAD

**Issue by Extrodox** [ASPLes/nopoll#8]
./config.status: line 561: syntax error near unexpected token `*-*-beos*'
./config.status: line 561: `  *-*-beos*)'

**Comment by francisbrosnan** [comment]
Hello,

Please, post more information about how are you running it, what's the OS
where you get that error, shell you are using, etc, etc.

Best Regards,

**Comment by francisbrosnan** [comment]
Closing issue until more information is provided,
Best Regards,

**Comment by Extrodox** [comment]
We are using it on Mac os x El Capitan.
